### ISSUE TITLE
OBi1032 Status Not Retrieved

### ISSUE THREAD

**Issue by rh8056** [dshokouhi/pyobihai#1]
When I view DI_S_.xml on the IP address of my OBi1032, the XML is like this:

https://pastebin.com/Ty6RAtRb

When I enable the integratation with Home Assistant, my logs spit out this error:

2020-01-19 11:54:27 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform obihai
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1630, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 3, column 58

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/obihai/sensor.py", line 58, in setup_platform
    line_services = pyobihai.get_line_state()
  File "/usr/local/lib/python3.7/site-packages/pyobihai/__init__.py", line 72, in get_line_state
    root = xml.etree.ElementTree.fromstring(resp.text)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1632, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1531, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 3, column 58
`

Please let me know what other information would be helpful to troubleshoot.  Thanks!

**Comment by dshokouhi** [comment]
What about this file `PI_FXS_1_Stats.xml` you should find it when you go to the Phone Port Status page

![image](https://user-images.githubusercontent.com/1634145/76909142-a9eca580-6867-11ea-8f91-7266d79daf85.png)

**Comment by rh8056** [comment]
That page (PI_FXS_1_Stats.xml) doesn't exist.  When I go to the similar section on the OB1032, I see a Line Status.  When I click that it loads PI_FXO_1_Stats.xml.

![image](https://user-images.githubusercontent.com/25002758/76910366-0b624380-686b-11ea-89b8-285717e0916a.png)

![image](https://user-images.githubusercontent.com/25002758/76910374-0f8e6100-686b-11ea-92ce-cb9a8f9bfc59.png)

**Comment by dshokouhi** [comment]
Hmm does the data ever populate there? Odd I was expecting to see On Hook or something in the state section.

**Comment by rh8056** [comment]
It doesn't appear to update at all, even when I make a call.

It appears that DI_S_.xml is updated and callstatus.htm is updated to have the information of the call itself.

**Comment by dshokouhi** [comment]
are you able to modify system files in your HA install?

**Comment by rh8056** [comment]
Yes, I can modify the files within HA.

**Comment by dshokouhi** [comment]
Actually think I found a viable fix for this.  Can you try this as a custom component?  It should work and just skip the sensors that do not exist.  Once you confirm I will get ready to submit to HA.  I tested it once from my end and seems to have worked well.

https://github.com/dshokouhi/home-assistant-obihai

**Comment by rh8056** [comment]
That worked great!

<img width="363" alt="image" src="https://user-images.githubusercontent.com/25002758/76996780-59c91e00-690f-11ea-92c3-0b9ae63021e6.png">

**Comment by dshokouhi** [comment]
This will be fixed in HA 0.108 :)
